"""Mark a stage's read-only tables const so they live in flash, not DRAM.

On the ESP32-S3, initialised non-const data is copied into internal DRAM at
boot, and there is only ~320 KB of it. A stage's compressed graphics,
palettes and sprite tables are read-only, but the decomp declares them plain
(`u8 e_merman_g0[]`), so each linked stage costs its whole art budget in DRAM
- NP3 alone was 201 KB and overflowed the link by 160 KB. `const` moves them
to flash rodata at zero runtime cost. NZ0 was done by hand in an earlier
round; this makes it repeatable, which matters because gen/sprites.c is
regenerated by the asset tool and loses any hand edit.

Usage: python esp32/const_stage_tables.py            (= nz0 np3 ric)
       python esp32/const_stage_tables.py np3 [more stages...]
"""
import re, sys, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
RULES = [
    (re.compile(r"^(u8|u16) (\w+\[\])", re.M), r"const \1 \2"),
    (re.compile(r"^s16\* (\w+\[\])", re.M), r"const s16* \1"),
    # sized too: gen/sprites.c forward-declares each part as `static s16 x[14];`
    (re.compile(r"^static s16 (\w+\[\d*\])", re.M), r"static const s16 \1"),
]
# Tile data lives in generated headers #included by stage_data.c, so the
# rules above never see it: the per-room tilemaps (u16) and the four byte
# arrays behind each TileDefinition. That was another 80 KB for NP3. The maps
# ARE mutated in game (doors, breakable walls) but only through the per-room
# writable copy made in SetRoomForegroundLayer (dra/4CE2C.c, ESP arm), so the
# originals can be const - NZ0 has shipped this way. The TileDefinition table
# itself stays writable: it only holds pointers and is small.
TILE_RULES = [
    (re.compile(r"^u16 (\w+\[\])", re.M), r"const u16 \1"),
    (re.compile(r"^static unsigned char (\w+\[\])", re.M),
     r"static const unsigned char \1"),
]
# Richter's sprite frames (the prologue character) are 85 KB of read-only
# pixel data that are never touched in normal play; left writable they alone
# were a quarter of all DRAM. `ric` as an argument handles them.
RIC_RULE = (re.compile(r"^static unsigned char (richter_\d+\[\d*\])", re.M),
            r"static const unsigned char \1")

args = sys.argv[1:] or ["nz0", "np3", "ric"]
for st in args:
    if st == "ric":
        p = ROOT / "src" / "ric" / "gen" / "richter.h"
        t, n = RIC_RULE[0].subn(RIC_RULE[1], p.read_text(encoding="utf-8"))
        p.write_text(t, encoding="utf-8")
        print(f"src/ric/gen/richter.h: {n} tablas marcadas const")
        continue
    gen = ROOT / "src" / "st" / st / "gen"
    tiles = sorted(gen.glob(f"{st}_tilemap_*.h")) + sorted(gen.glob(f"{st}_tiledef_*.h"))
    n = 0
    for p in tiles:
        t = p.read_text(encoding="utf-8")
        for rx, rep in TILE_RULES:
            t, k = rx.subn(rep, t); n += k
        p.write_text(t, encoding="utf-8")
    print(f"src/st/{st}/gen/*tilemap*/*tiledef*: {n} tablas marcadas const")
    for rel in (f"src/st/{st}/stage_data.c", f"src/st/{st}/gen/sprites.c"):
        p = ROOT / rel
        s = p.read_text(encoding="utf-8")
        n = 0
        for rx, rep in RULES:
            s, k = rx.subn(rep, s); n += k
        p.write_text(s, encoding="utf-8")
        print(f"{rel}: {n} tablas marcadas const")
