# Auto-generated: globals defined by MORE THAN ONE static stage.
# Each stage gets its own -D rename so the linker cannot cross-wire
# them (NZ0 once ran WRP's HitDetection because of this).
# CAREFUL: the .obj files already carry renamed symbols, so a fresh
# nm intersection returns only NEW ones - always union with this list.
set(STAGE_DUP_SYMS
    AdjustValueWithinThreshold
    AllocEntity
    AnimateEntity
    BackgroundBlockInit
    BlitChar
    BottomCornerText
    CheckColliderOffsets
    CheckFieldCollision
    ClutLerp
    CollectGold
    CollectHeartVessel
    CreateEntityFromCurrentEntity
    CreateEntityFromEntity
    CreateEntityFromLayout
    CreateEntityWhenInHorizontalRange
    CreateEntityWhenInVerticalRange
    EntityBackgroundBlock
    EntityBigRedFireball
    EntityCutscene
    EntityDamageDisplay
    EntityDummy
    EntityEnemyBlood
    EntityEquipItemDrop
    EntityExplosion
    EntityExplosionSpawn
    EntityExplosionVariants
    EntityExplosionVariantsSpawner
    EntityGreyPuff
    EntityGreyPuffSpawner
    EntityHeartDrop
    EntityIntenseExplosion
    EntityLockCamera
    EntityMessageBox
    EntityOlroxDrool
    EntityPrizeDrop
    EntityRedDoor
    EntityRelicOrb
    EntityRoomForeground
    EntitySoulStealOrb
    EntityStageNamePopup
    EntityUnkId13
    EntityUpdates
    FallEntity
    FindFirstUnkPrim
    FindFirstUnkPrim2
    GetAngleBetweenEntities
    GetAngleBetweenEntitiesShifted
    GetAnglePointToEntity
    GetAnglePointToEntityShifted
    GetDistanceToPlayerX
    GetDistanceToPlayerY
    GetPlayerCollisionWith
    GetSideToPlayer
    GetSine
    GetSineScaled
    HitDetection
    InitRoomEntities
    InitializeEntity
    InitializeUnkEntity
    LimitAngleChange
    MakeEntityFromId
    MakeExplosions
    MoveEntity
    PlaySfxPositional
    PreventEntityFromRespawning
    PrimDecreaseBrightness
    PrimResetNext
    PrimToggleVisibility
    PrizeDrops
    Random
    Ratan2
    Ratan2Shifted
    ReplaceBreakableWithItemDrop
    SetCutsceneEvents
    SetEntityVelocityFromAngle
    SetStep
    SetSubStep
    UNK_Invincibility0
    UnkAnimFunc
    UnkCollisionFunc
    UnkCollisionFunc2
    UnkCollisionFunc3
    UnkCollisionFunc4
    UnkCollisionFunc5
    UnkEntityFunc0
    UnkPolyFunc0
    UnkPolyFunc2
    UnkPrimHelper
    UnkRecursivePrimFunc1
    UnkRecursivePrimFunc2
    Update
    UpdateAnimation
    UpdateRoomPosition
    UpdateStageEntities
    c_HeartPrizes
    entityLayoutHorizontal
    entityLayoutVertical
    g_Dialogue
    g_EInitBreakable
    g_EInitCommon
    g_EInitDamageNum
    g_EInitEnemy3
    g_EInitInteractable
    g_EInitLockCamera
    g_EInitObtainable
    g_EInitParticle
    g_EInitSpawner
    g_EInitUnkId13
    g_ESoulStealOrbAngles
    g_ESoulStealOrbAnim
    g_ESoulStealOrbSprt
    g_ItemIconSlots
    g_RedDoorTiles
    g_RelicOrbSparkleX
    g_RelicOrbSparkleY
    g_RelicOrbTextBg1EY
    g_RelicOrbTextBg1SY
    g_RelicOrbTextBg2EY
    g_RelicOrbTextBg2SY
    g_RelicOrbTexts
    g_SkipCutscene
    g_SubweaponAnimPrizeDrop
    g_bigRedFireballAnim
    g_explosionBigAnim
    g_goldCollectTexts
    rooms
    # NP3 vs NZ0/WRP/SEL (nm intersection, 2026-09-27) - includes 15 functions
    # the linker resolved SILENTLY to the wrong stage (EntitySlogra, ...)
    CreateExplosionPuff
    EntityBloodDrips
    EntityBloodSplatter
    EntityBloodyZombie
    EntityBoneScimitar
    EntityBoneScimitarParts
    EntityBreakable
    EntityExplosionPuffOpaque
    EntityGaibon
    EntityGaibonLeg
    EntityLargeGaibonProjectile
    EntitySlogra
    EntitySlograSpear
    EntitySlograSpearProjectile
    EntitySmallGaibonProjectile
    e_bloody_zombie_g
    e_bloody_zombie_p
    e_explosion_g
    e_explosion_p
    e_gaibon_g0
    e_gaibon_g1
    e_gaibon_p
    e_slinger_g
    e_slinger_p
    e_slogra_g0
    e_slogra_g1
    e_slogra_g2
    e_slogra_p
    g_EInitBloodyZombie
    g_EInitBoneScimitar
    g_EInitScimitarParts
)
